alg_name: "FT"
model_name: "./hugging_cache/gpt-j-6B"
device: 0

layers: [0]
num_steps: 25
batch_size: 1
max_length: 30
lr: 5e-4
weight_decay: 0
kl_factor: 0
norm_constraint: 3.5e-4
rewrite_module_tmp: "transformer.h.{}.mlp.fc_out"
layer_module_tmp: "transformer.h.{}"
mlp_module_tmp: "transformer.h.{}.mlp"
attn_module_tmp: "transformer.h.{}.attn"
ln_f_module: "transformer.ln_f"
lm_head_module: "lm_head"