relationid_words={
'P36': ['has capital',"is the capital of"],
'P26': ['the spouse of','the spouse of'],
'P38': ['the currency',"the currency of"],
'P169': ['chief executive officer',"the CEO of"],
'P35': ['head of state or government',"is the head of"],
'P634': ['team captain',"the captain of"],
'P185': ['doctoral student', "doctoral student of"],
'P1429': ['has pet',"the pet of"],
'P355': ['has subsidiary',"the subsidiary of"],
'P112': ['founded by',"has founded"],
'P39': ['holds the position', "is held by"],
'P277': ['the programming language written',"the programming language of"],
'P2389': ['is directed from',"directs"],
'P86': ['the composer of', "is the composer of"],
'P162': ['produced by', 'has produced'],
'P108': ['is employed by', "has employer"],
'P119': ['The burial place of', "is the burial place"],
'P110': ['the illustrator', 'was illustrated by'],
'P749': ['parent organization', "is the parent organization of"],
'P287': ['designed by', "has designed"],
'P37': ['official language is',"is the official language of"],
'P103': ['native language', "is the native language of"],
'P176': ['manufactured by', 'has manufactured'],
'P1589': ['the lowest point of',"is the lowest point of"],
'P50': ['has author', "the author of"],
'P47': ['shares border with',"shares border with"],
'P1327': ['partner in business or sport',""],
'P530': ['diplomatic relation','diplomatic relation'],
'P190': ['twinned administrative body','twinned administrative body'],
're_P112': ['has founded','founded by'],
're_P39': ['is held by','holds the position'],
're_P277': ['is the programming language of','the programming language written'],
're_P2389': ['is the head of','is directed from'],
're_P86': ['is the composer of','the composer of'],
're_P162': ['has produced', 'produced by'],
're_P108': ['has employed', 'is employed by'],
're_P119': ['is the burial place of', 'The burial place of'],
're_P110': ['was illustrated by', 'the illustrator'],
're_P749': ['is the parent organization','parent organization'],
're_P287': ['has designed', 'designed by'],
're_P37': ['is the official language of', 'official language is'],
're_P103': ['is the native language of', 'native language'],
're_P176': ['has manufactured', 'manufactured by'],
're_P1589': ['is the lowest point of', 'the lowest point of'],
're_P50': ["the author of", 'has author'],
}